version: '3.9'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    depends_on:
      - application-db-postgres

  application-db-postgres:
    container_name: application-db-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres-application-data:/var/lib/postgresql/data

volumes:
  postgres-application-data:
