# Utiliza una imagen base de Java
FROM openjdk:17-jdk-slim

# Copia el archivo JAR de tu API a la imagen
COPY ./api-1.jar /app/api-1.jar

# Establece el directorio de trabajo
WORKDIR /app

# Expone el puerto en el que se ejecuta la API
EXPOSE 8080

# Comando para ejecutar la API
CMD ["java", "-jar", "api-1.jar"]
