version: '3.9'

services:
  application-db:
    container_name: application-db
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - mysql-application-data:/var/lib/mysql

volumes:
  mysql-application-data: